// Design System 2025 - Export centralisé des composants
export { default as AdminModal } from './AdminModal.vue'
export { default as Alert } from './Alert.vue'
export { default as Badge } from './Badge.vue'
export { default as Button } from './Button.vue'
export { default as Card } from './Card.vue'
export { default as Checkbox } from './Checkbox.vue'
export { default as ConfirmDialog } from './ConfirmDialog.vue'
export { default as DashboardLayout } from './DashboardLayout.vue'
export { default as Dropdown } from './Dropdown.vue'
export { default as EmptyState } from './EmptyState.vue'
export { default as Footer } from './Footer.vue'
export { default as Form } from './Form.vue'
export { default as Grid } from './Grid.vue'
export { default as Input } from './Input.vue'
export { default as Label } from './Label.vue'
export { default as Loading } from './Loading.vue'
export { default as Modal } from './Modal.vue'
export { default as Navigation } from './Navigation.vue'
export { default as NotificationContainer } from './NotificationContainer.vue'
export { default as PageTransition } from './PageTransition.vue'
export { default as ProductCard } from './ProductCard.vue'
export { default as Pagination } from './Pagination.vue'
export { default as Select } from './Select.vue'
export { default as Skeleton } from './Skeleton.vue'
export { default as Textarea } from './Textarea.vue'
export { default as Table } from './Table.vue'
export { default as Tabs } from './Tabs.vue'
export { default as Tooltip } from './Tooltip.vue'
export { default as ThemeToggle } from './ThemeToggle.vue'
export { default as MobileBottomNav } from './MobileBottomNav.vue'

// Types exports
export type { ButtonVariant, ButtonSize } from './Button.vue'
export type { CardVariant } from './Card.vue'
export type { BadgeVariant, BadgeSize } from './Badge.vue'
export type { InputSize, InputVariant } from './Input.vue'
export type { LabelSize, LabelVariant } from './Label.vue'
export type { SelectSize, SelectVariant } from './Select.vue'
export type { TextareaSize, TextareaVariant } from './Textarea.vue'
export type { ModalSize, ModalVariant } from './Modal.vue'
export type { ConfirmDialogType } from './ConfirmDialog.vue'
export type { TableColumn } from './Table.vue'
export type { DropdownItem, DropdownPlacement, DropdownSize, DropdownVariant } from './Dropdown.vue'
export type { TooltipPlacement, TooltipVariant } from './Tooltip.vue'
export type { LoadingType, LoadingSize, LoadingVariant } from './Loading.vue'
export type { EmptyStateAction, EmptyStateSize, EmptyStateVariant } from './EmptyState.vue'
export type { Tab } from './Tabs.vue'
export type { FormSize, FormVariant } from './Form.vue'
export type { GridCols, GridGap, GridAlign, GridJustify } from './Grid.vue'
export type { ProductCardTag, ProductCardBadge } from './ProductCard.vue'
export type { ThemeMode } from './ThemeToggle.vue'
export type { NavigationLink, NavigationBrand, NavigationCta } from './Navigation.vue'
export type { FooterLink, FooterBrand, SocialNetwork } from './Footer.vue'
