#!/usr/bin/env node
/**
 * Generate test report from test results
 * Creates both Markdown and HTML reports with embedded screenshots
 */

import * as fs from 'fs';
import * as path from 'path';

interface TestResult {
  name: string;
  status: 'pass' | 'fail' | 'skip';
  duration: number;
  error?: string;
  screenshots: string[];
}

interface TestReport {
  startTime: string;
  endTime?: string;
  duration?: number;
  device: string;
  scenario: string;
  results: TestResult[];
  totalTests: number;
  passed: number;
  failed: number;
  skipped: number;
}

const REPORT_DATA_PATH = path.join(__dirname, '../test-results/report-data.json');
const REPORT_MD_PATH = path.join(__dirname, '../test-results/TEST_REPORT.md');
const REPORT_HTML_PATH = path.join(__dirname, '../test-results/TEST_REPORT.html');

/**
 * Load report data
 */
function loadReportData(): TestReport | null {
  try {
    const data = fs.readFileSync(REPORT_DATA_PATH, 'utf-8');
    return JSON.parse(data);
  } catch (error) {
    console.error('❌ Failed to load report data:', error);
    return null;
  }
}

/**
 * Generate Markdown report
 */
function generateMarkdown(report: TestReport): string {
  const passRate = report.totalTests > 0 ? ((report.passed / report.totalTests) * 100).toFixed(1) : '0.0';

  let md = `# 📱 Antigaspi Mobile - Test Report\n\n`;
  md += `**Date:** ${new Date(report.startTime).toLocaleString()}\n\n`;
  md += `**Device:** ${report.device}\n\n`;
  md += `**Scenario:** ${report.scenario}\n\n`;
  md += `**Duration:** ${(report.duration! / 1000).toFixed(1)}s\n\n`;
  md += `---\n\n`;

  md += `## 📊 Summary\n\n`;
  md += `| Metric | Value |\n`;
  md += `|--------|-------|\n`;
  md += `| Total Tests | ${report.totalTests} |\n`;
  md += `| ✅ Passed | ${report.passed} |\n`;
  md += `| ❌ Failed | ${report.failed} |\n`;
  md += `| ⏭️ Skipped | ${report.skipped} |\n`;
  md += `| Pass Rate | ${passRate}% |\n\n`;

  md += `---\n\n`;
  md += `## 🧪 Test Results\n\n`;

  report.results.forEach((result, index) => {
    const icon = result.status === 'pass' ? '✅' : result.status === 'fail' ? '❌' : '⏭️';
    md += `### ${index + 1}. ${icon} ${result.name}\n\n`;
    md += `- **Status:** ${result.status.toUpperCase()}\n`;
    md += `- **Duration:** ${(result.duration / 1000).toFixed(1)}s\n`;

    if (result.error) {
      md += `- **Error:** \`${result.error}\`\n`;
    }

    if (result.screenshots.length > 0) {
      md += `\n**Screenshots:**\n\n`;
      result.screenshots.forEach((screenshot, idx) => {
        const relPath = path.relative(path.join(__dirname, '../test-results'), screenshot);
        md += `![Screenshot ${idx + 1}](${relPath})\n\n`;
      });
    }

    md += `\n---\n\n`;
  });

  md += `\n## 🤖 Generated by Antigaspi App Tester\n`;
  md += `Automated testing powered by mobile-mcp and adb-mcp\n`;

  return md;
}

/**
 * Generate HTML report
 */
function generateHTML(report: TestReport): string {
  const passRate = report.totalTests > 0 ? ((report.passed / report.totalTests) * 100).toFixed(1) : '0.0';

  let html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Antigaspi Mobile - Test Report</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 1200px;
      margin: 0 auto;
      padding: 20px;
      background: #f5f5f5;
    }
    .container {
      background: white;
      border-radius: 8px;
      padding: 30px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    }
    h1 { color: #10b981; margin-bottom: 20px; }
    h2 { color: #059669; margin-top: 30px; margin-bottom: 15px; border-bottom: 2px solid #10b981; padding-bottom: 10px; }
    h3 { color: #047857; margin-top: 20px; margin-bottom: 10px; }
    .meta { background: #f0fdf4; padding: 15px; border-radius: 6px; margin-bottom: 20px; }
    .meta p { margin: 5px 0; }
    .meta strong { color: #047857; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { padding: 12px; text-align: left; border-bottom: 1px solid #e5e7eb; }
    th { background: #f0fdf4; color: #047857; font-weight: 600; }
    .pass { color: #10b981; font-weight: bold; }
    .fail { color: #ef4444; font-weight: bold; }
    .skip { color: #f59e0b; font-weight: bold; }
    .test-result { background: #fafafa; padding: 20px; border-radius: 6px; margin: 15px 0; border-left: 4px solid #10b981; }
    .test-result.fail { border-left-color: #ef4444; }
    .test-result h3 { margin-top: 0; }
    .test-details { margin: 10px 0; }
    .test-details p { margin: 5px 0; }
    .error { background: #fee2e2; color: #991b1b; padding: 10px; border-radius: 4px; margin: 10px 0; font-family: monospace; font-size: 14px; }
    .screenshots { margin-top: 15px; }
    .screenshots img { max-width: 100%; height: auto; border-radius: 6px; margin: 10px 0; box-shadow: 0 2px 6px rgba(0,0,0,0.1); }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; text-align: center; color: #6b7280; font-size: 14px; }
    .badge { display: inline-block; padding: 4px 12px; border-radius: 12px; font-size: 14px; font-weight: 600; }
    .badge-pass { background: #d1fae5; color: #065f46; }
    .badge-fail { background: #fee2e2; color: #991b1b; }
    .badge-skip { background: #fef3c7; color: #92400e; }
  </style>
</head>
<body>
  <div class="container">
    <h1>📱 Antigaspi Mobile - Test Report</h1>

    <div class="meta">
      <p><strong>Date:</strong> ${new Date(report.startTime).toLocaleString()}</p>
      <p><strong>Device:</strong> ${report.device}</p>
      <p><strong>Scenario:</strong> ${report.scenario}</p>
      <p><strong>Duration:</strong> ${(report.duration! / 1000).toFixed(1)}s</p>
    </div>

    <h2>📊 Summary</h2>
    <table>
      <thead>
        <tr>
          <th>Metric</th>
          <th>Value</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Total Tests</td>
          <td>${report.totalTests}</td>
        </tr>
        <tr>
          <td>✅ Passed</td>
          <td class="pass">${report.passed}</td>
        </tr>
        <tr>
          <td>❌ Failed</td>
          <td class="fail">${report.failed}</td>
        </tr>
        <tr>
          <td>⏭️ Skipped</td>
          <td class="skip">${report.skipped}</td>
        </tr>
        <tr>
          <td>Pass Rate</td>
          <td><strong>${passRate}%</strong></td>
        </tr>
      </tbody>
    </table>

    <h2>🧪 Test Results</h2>
`;

  report.results.forEach((result, index) => {
    const badgeClass = result.status === 'pass' ? 'badge-pass' : result.status === 'fail' ? 'badge-fail' : 'badge-skip';
    const resultClass = result.status === 'fail' ? 'fail' : '';

    html += `
    <div class="test-result ${resultClass}">
      <h3>${index + 1}. ${result.name} <span class="badge ${badgeClass}">${result.status.toUpperCase()}</span></h3>
      <div class="test-details">
        <p><strong>Duration:</strong> ${(result.duration / 1000).toFixed(1)}s</p>
`;

    if (result.error) {
      html += `        <div class="error">${result.error}</div>\n`;
    }

    if (result.screenshots.length > 0) {
      html += `        <div class="screenshots">\n`;
      html += `          <p><strong>Screenshots:</strong></p>\n`;
      result.screenshots.forEach((screenshot, idx) => {
        const relPath = path.relative(path.join(__dirname, '../test-results'), screenshot);
        html += `          <img src="${relPath}" alt="Screenshot ${idx + 1}" />\n`;
      });
      html += `        </div>\n`;
    }

    html += `
      </div>
    </div>
`;
  });

  html += `
    <div class="footer">
      <p>🤖 Generated by Antigaspi App Tester</p>
      <p>Automated testing powered by mobile-mcp and adb-mcp</p>
    </div>
  </div>
</body>
</html>`;

  return html;
}

/**
 * Main function
 */
function main() {
  console.log('📝 Generating test report...\n');

  const report = loadReportData();
  if (!report) {
    console.error('❌ No report data found');
    process.exit(1);
  }

  try {
    // Generate Markdown
    const markdown = generateMarkdown(report);
    fs.writeFileSync(REPORT_MD_PATH, markdown, 'utf-8');
    console.log(`✅ Markdown report: ${REPORT_MD_PATH}`);

    // Generate HTML
    const html = generateHTML(report);
    fs.writeFileSync(REPORT_HTML_PATH, html, 'utf-8');
    console.log(`✅ HTML report: ${REPORT_HTML_PATH}`);

    console.log('\n✨ Reports generated successfully!');
  } catch (error) {
    console.error('❌ Failed to generate reports:', error);
    process.exit(1);
  }
}

main();
